vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        products_images:
            uri_prefix: "%products_images%"
            upload_destination: "%kernel.project_dir%/public/%products_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        colletion_images:
            uri_prefix: "%colletion_images%"
            upload_destination: "%kernel.project_dir%/public%colletion_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        review_images:
            uri_prefix: "%review_images%"
            upload_destination: "%kernel.project_dir%/public%review_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
